---
output: github_document
---

```{r knitr setup, include=FALSE}
# set default knitr options for this file
knitr::opts_chunk$set(echo = TRUE,  # show output after code chunks
                      results = "hold")  # hold results until after chunk is run
```

# Cleaning the "behavior" table

### Code only

[**Go to Project Summary**](../readme.md)

```{r libraries, message=FALSE}
library(readr)
library(dplyr)

cat("libraries loaded\n")

behavior <- read_delim("../original-data/DiverReef_behavior_data.csv",
                       delim = ";")

cat("data loaded")
```

```{r behavior}
glimpse(behavior)
```

```{r}
behavior <- behavior %>%
  rename(
    gender = sex,
    samp_time_min = samp_timing_min,
    total_interactions = total
  )

colnames(behavior)
```

```{r diver id beh.}
length(unique(behavior$diver_id))  # check number of unique diver_id
class(behavior$diver_id)

# check the range of values in diver_id
min(behavior$diver_id)
max(behavior$diver_id)
```

```{r gender}
unique(behavior$gender)
class(behavior$gender)
```

```{r}
behavior <- behavior %>%
  mutate(gender = as.factor(gender))  # convert to factor

class(behavior$gender)
```

```{r experience}
class(behavior$experience)
min(behavior$experience, na.rm = TRUE)  # ignore NA values
max(behavior$experience, na.rm = TRUE)
```

```{r camera}
unique(behavior$camera)
class(behavior$camera)
```

```{r}
behavior <- behavior %>%
  mutate(camera = as.factor(camera))

class(behavior$camera)
```

```{r sampling time}
class(behavior$samp_time_min)
min(behavior$samp_time_min, na.rm = TRUE)
max(behavior$samp_time_min, na.rm = TRUE)
```

```{r interactions}
cat(" damage:\n")
class(behavior$damage)
min(behavior$damage, na.rm = TRUE)
max(behavior$damage, na.rm = TRUE)

cat("\n contact:\n")
class(behavior$contact)
min(behavior$contact, na.rm = TRUE)
max(behavior$contact, na.rm = TRUE)

cat("\n total_interactions:\n")
class(behavior$total_interactions)
min(behavior$total_interactions, na.rm = TRUE)
max(behavior$total_interactions, na.rm = TRUE)
```

```{r}
# total number of observations
a <- nrow(behavior)

# count records where damage + contact == total_interactions
b <- nrow(behavior %>% filter(damage + contact == total_interactions))

# percentage of observations where damage + contact == total_interactions
cat("percentage of records where damage + contact == total_interactions:\n")
b / a * 100

# check if there are any records where total_interactions is NA
cat("number of records where total_interactions is NA:\n")
nrow(behavior %>% filter(is.na(total_interactions)))
```

```{r}
# count records where damage AND contact is NA
c <- nrow(behavior %>% filter(is.na(damage) & is.na(contact)))

# percentage of observations where damage AND contact are NA
c / a * 100
```

```{r}
# first scenario
# count records where neither damage or contact is NA
# and they don't add up to total_interactions
d <- nrow(behavior %>% filter(damage + contact != total_interactions))

# second scenario: total
# count records where only one of damage or contact is NA
e <- nrow(behavior %>% filter(xor(is.na(damage), is.na(contact))))

# percentage of observations that have no plausible explanation
# for entries in these fields
cat(" percentage where entries in damage, contact or total_interactions don't make sense:\n")
(d + e) / a * 100


# second scenario: special cases
# count records where only one of damage or contact is NA
# AND that field is equal to total_interactions
cat("\n number of plausible records where only one of damage or contact is NA:\n")
nrow(behavior %>%
       filter(xor(is.na(damage), is.na(contact)) &
                ((damage | contact) == total_interactions)))

# did I get everything?
cat("\n did I account for all of the data?\n")
a == b + c + d + e
```

```{r}
# select only records where the two conditions reasoned before are met
behavior <- behavior %>%
  filter(
    # if damage + contact == total_interactions OR
    (damage + contact == total_interactions) |
      # if damage AND contact are NA
      (is.na(damage) & is.na(contact)))
```

```{r}
cat("damage:\n")
max(behavior$damage, na.rm = TRUE)

cat("contact:\n")
max(behavior$contact, na.rm = TRUE)

cat("total interactions:\n")
max(behavior$total_interactions, na.rm = TRUE)
```

```{r}
# check records with high total_interactions numbers
behavior %>%
  filter(total_interactions > 300) %>%  # 300 is arbitrary
  select(-gender)  # only for total_interactions to fit in the output
```

```{r}
behavior <- behavior %>%
  # create interactions_per_min and round to 4 digits
  mutate(interactions_per_min = round(total_interactions / samp_time_min, 4))
```

```{r}
# check max interactions_per_min values when sampling time was less than 10 min
behavior %>%
  filter(samp_time_min < 10) %>%
  summarize(max(interactions_per_min)) %>%
  pull()  # show only the result instead of the data frame
```

```{r}
# total number of records that will be dropped
nrow(behavior %>% filter(interactions_per_min > 12))

# select only observations with values in interactions_per_min less than 12
behavior <- behavior %>%
  filter(interactions_per_min <= 12)
```

```{r}
glimpse(behavior)
```

[**Go to Project Summary**](../readme.md)
